### ISSUE TITLE
[RFE] ci: Avoid running workflow when not needed

### ISSUE THREAD

**Issue by blanquicet** [Azure/kubectl-aks#32]
For instance, PR https://github.com/Azure/kubectl-aks/pull/27 only updated README and the krew manifest. In that case, workflow doesn't need to run. Same if only files under docs are modified, etc.

**Comment by mqasimsarfraz** [comment]
One possible implementation can be to use [paths](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-files-changed-in-a-pull-request) filter to trigger the CI e.g:

```
on:
  pull_request:
    paths:
      - '**.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - main
    tags:
      - 'v*'
```

Or may be we are allowed to exclude paths using `paths` as well?
